<div>
    <?php echo $block->getButtonHtml() ?>
    <span class="collect-indicator" id="collect_span_import_atualizacao">
        <img
            class="processingImportAtualizacao"
            hidden="hidden"
            alt="CollectedImportAtualizacao"
            style="margin:0 5px"
            src="<?php echo $block->getViewFileUrl('images/process_spinner.gif') ?>"
        />
        <img
            class="CollectedImportAtualizacao"
            hidden="hidden" alt="CollectedImportAtualizacao"
            style="margin:-3px 5px"
            src="<?php echo $block->getViewFileUrl('images/rule_component_apply.gif') ?>"
        />
        <span
            style="color: red"
            id="collect_message_span_import_atualizacao"
        />
    </span>
</div>

<script>
    require([
        'jquery',
        'prototype'
    ], function(jQuery){

        var collectSpan = jQuery('#collect_span_import_atualizacao');

        jQuery('#execute_atualizacao').click(function () {
            var params = {};
            new Ajax.Request('<?php echo $block->getUrlExecutarAtualizacao() ?>', {
                parameters:     params,
                loaderArea:     false,
                asynchronous:   true,
                onCreate: function() {
                    collectSpan.find('.CollectedImportAtualizacao').hide();
                    collectSpan.find('.processingImportAtualizacao').show();
                    jQuery('#collect_message_span_import_atualizacao').text('');
                },
                onSuccess: function(response) {
                    collectSpan.find('.processingImportAtualizacao').hide();
                    var response = JSON.parse(response.responseText);
                    var resultText = '';
                    if (response.status > 200) {
                        resultText = response.error_message;
                    } else {
                        resultText = response.sucess_message;
                        collectSpan.find('.CollectedImportAtualizacao').show();

                    }
                    jQuery('#collect_message_span_import_atualizacao').text(resultText);

                    var json = response.responseJson;

                    if (typeof json.time != 'undefined') {
                        jQuery('#row_mageworx_alsobought_general_collect_time').find('.value .time').text(json.time);
                    }
                }
            });
        });

    });
</script>
